# Generated by Django 6.0 on 2026-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehero',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
