# Generated by Django 6.0 on 2026-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('cabin', 'Cabin'), ('studio', 'Studio'), ('bed&breakfast', 'Bed&Breakfast'), ('loft', 'Loft')], default='', max_length=20),
        ),
    ]
